# Generated by Django 2.2.12 on 2020-05-05 16:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('title', m models.CharField("Заголовок", max_length=200,default="")),
                ('text', models.TextField(max_length=1500)),
                ('create', models.DateTimeField("Создан", auto_now_add=True)),
                ('short', models.TextField("Краткое содержание", max_length=1000)),
                ('update', models.DateTimeField("Обновлено",auto_now=True)),
                ('moder', models.BooleanField("Модерация", default=False)),
                ('image', mmodels.ImageField("Изображение", upload_to="blog" , blank=True)),
            ],
        ),
    ]
