# Generated by Django 2.2.12 on 2020-05-16 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200514_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='short',
            field=models.TextField(default=1, max_length=1000, verbose_name='Краткое содержание'),
            preserve_default=False,
        ),
    ]
